spring:
  data:
    redis:
      host: localhost
      port: 6379

redisx:
  cache:
    prefix: zeng-cache         # prefix สำหรับทุก key เช่น zeng-cache:user:123
    default-ttl-seconds: 300   # TTL เริ่มต้นถ้า annotation ไม่กำหนด (วินาที)
    enabled: true              # เปิด/ปิดระบบ cache ทั้งชุด
    cache-null: false          # ให้ cache ค่า null หรือไม่
    null-ttl-seconds: 30       # TTL ของ null-value (เมื่อ cache-null=true)

logging:
  level:
    org.springframework.data.redis: WARN        # เห็นคำสั่ง GET/SET
    io.lettuce.core: WARN                       # เห็นระดับ client
    com.zengcode.redisx: DEBUG